In [40]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Review of Tables ##

In [41]:
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [42]:
point_guards = nba.where('position', 'PG')

In [43]:
point_guards

rank | name             | position | team                   | salary   | season
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | PG       | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | PG       | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | PG       | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | PG       | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | PG       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | PG       | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | PG       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | PG       | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | PG       | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [44]:
point_guards.drop('position')

rank | name             | team                   | salary   | season
8    | Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [45]:
point_guards

rank | name             | position | team                   | salary   | season
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | PG       | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | PG       | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | PG       | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | PG       | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | PG       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | PG       | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | PG       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | PG       | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | PG       | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [46]:
point_guards = point_guards.drop('position')

In [47]:
point_guards.sort('salary', descending=True).show()

In [48]:
point_guards.sort('salary', descending=True).show(15)

In [49]:
# Errors!
nba.where('Position', 'PG')

ValueError: label "Position" not in labels ('rank', 'name', 'position', 'team', 'salary', 'season')

In [ ]:
nba.drop('position').where('position', 'PG')

## Numbers ##

In [51]:
30

30

In [52]:
10 * 3    # int

30

In [53]:
10 / 3    # float

3.3333333333333335

In [54]:
10 / 2

5.0

In [55]:
10 ** 3

1000

In [56]:
10 ** 0.5

3.1622776601683795

In [57]:
1234567 ** 890

ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [58]:
10 / 3

3.3333333333333335

In [59]:
75892745.215489247589274985712

75892745.21548925

In [60]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [61]:
(13 ** 0.5) ** 2

12.999999999999998

In [62]:
int(10 / 5)

2

In [63]:
int(10 / 4)

2

In [64]:
float(3)

3.0

In [65]:
6 / 4

1.5

In [66]:
6 / 4000

0.0015

In [67]:
6 / 400000000000000000000000000000000000000000000000000000000

1.5e-56

In [68]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56 

6.0

In [69]:
1.5e-56 

1.5e-56

In [70]:
x = 5

In [71]:
2x

SyntaxError: invalid decimal literal (207285602.py, line 1)

In [ ]:
2 * x

## Strings ##

In [72]:
'Flavor'

'Flavor'

In [73]:
Flavor

NameError: name 'Flavor' is not defined

In [74]:
"Flavor"

'Flavor'

In [75]:
'Don't always use single quotes'

SyntaxError: unterminated string literal (detected at line 1) (2648065634.py, line 1)

In [76]:
"Don't always use single quotes"

"Don't always use single quotes"

In [77]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

In [78]:
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [79]:
'ha' + 10

TypeError: can only concatenate str (not "int") to str

In [80]:
'ha' + str(10)

'ha10'

In [81]:
int('3')

3

In [82]:
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [83]:
int(float('3.0'))

3

## Types ##

In [84]:
type(10)

int

In [85]:
a = 10

In [86]:
type(a)

int

In [87]:
type(4.5)

float

In [88]:
type('abc')

str

In [89]:
type(nba)

datascience.tables.Table

In [90]:
type(True)

bool

In [91]:
abs(-5)

5

In [92]:
type(abs)

builtin_function_or_method

## Arrays ##

In [93]:
my_array = make_array(1, 2, 3, 4)

In [94]:
my_array

array([1, 2, 3, 4], dtype=int64)

In [95]:
my_array * 2

array([2, 4, 6, 8], dtype=int64)

In [96]:
my_array ** 2

array([ 1,  4,  9, 16], dtype=int64)

In [97]:
my_array + 1

array([2, 3, 4, 5], dtype=int64)

In [98]:
my_array # array is unchanged, just like when we call show/select/drop on Table

array([1, 2, 3, 4], dtype=int64)

In [99]:
another = make_array(5, 6, 7, 8)

In [100]:
my_array + another

array([ 6,  8, 10, 12], dtype=int64)

In [101]:
yet_another = make_array(5, 6, 7)

In [102]:
my_array + yet_another

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [103]:
sum(my_array)

10

In [104]:
np.average(my_array)

2.5

In [105]:
len(my_array)

4

In [106]:
tunas = make_array('bluefin', 'albacore', 'jim')
tunas

array(['bluefin', 'albacore', 'jim'],
      dtype='<U8')

In [107]:
tunas * 4

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U8'), dtype('int32')) -> None

In [108]:
tunas.item(0) # NOTE: indexing starts at 0!

'bluefin'

In [109]:
tunas.item(1)

'albacore'

In [110]:
tunas.item(2)

'jim'

## Columns of Tables are Arrays ##

In [111]:
warriors = nba.where('team', 'Golden State Warriors')

In [112]:
warriors

rank | name              | position | team                  | salary  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [113]:
warriors.select('salary')

salary
5250000
4988000
4200000
4200000
3937000
2600000
2503000
5611000
4800000
4800000
... (301 rows omitted)

In [114]:
type(warriors.select('salary'))

datascience.tables.Table

In [115]:
warriors.column('salary')

array([ 5250000,  4988000,  4200000,  4200000,  3937000,  2600000,
        2503000,  5611000,  4800000,  4800000,  4386000,  3578000,
        3390000,  2678000,  1842000,   757000,   316000,   316000,
         241000,    32000,  6235000,  5400000,  5400000,  4913000,
        4441000,  4400000,  3388000,  3000000,  2343000,  2021000,
        1310000,   333000,   333000,  6858000,  6000000,  5540000,
        4935000,  4469000,  4400000,  1409000,   700000,   512000,
       10912000,  7482000,  5445000,  4400000,  1667000,  1507000,
        3000000,  2481000,  2390000,  2232000, 13700000,  8888888,
        7365079,  7312500,  5393300,  4506261,  1988160,  1910520,
        1857360,  1760000,  1404360,   448762,   423762, 15070000,
        9999999,  8125000,  2535260,  2157097,  2061720,  1986960,
         798112,   744551,   664209,   259770, 16440000,  8425625,
        6630000,  4000000,  3470771,  3000000,  2636696,  2323080,
        2216400,  1800000,  1345800,   770610,   770610,   687

In [116]:
np.average(warriors.column('salary'))

4315935.9228295824

In [117]:
celtics = nba.where('team', 'Boston Celtics')

In [118]:
np.average(warriors.column('salary')) - np.average(celtics.column('salary'))

-753222.82997940667